# Generated by Django 4.2.7 on 2023-11-20 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile_date_userprofile_dob_userprofile_fname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='profielimg',
            new_name='profileimg',
        ),
    ]
